---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raffa-qrs2-dev
  namespace: myapp-build
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/raf-backstage-demo/raffa-qrs2
    targetRevision: HEAD
    path: .helm/chart
    helm:
      valueFiles:
        - ../value-files/values-dev.yaml
      values: |
        quarkus-run: 
          image:
            tag: db243ba4813f8f222ce4a9eeb039ddf1e45fccd0
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-dev
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy 
  ignoreDifferences:      
  - group: networking.istio.io
    kind: VirtualService
    name: raffa-qrs2
    namespace: myapp-dev
    jsonPointers:
    - /spec/hosts                     